<template>
	<Teleport to="body">
		<Transition name="preview-fade">
			<div v-if="doc" class="preview-backdrop" @click.self="$emit('close')">
				<Transition name="preview-slide">
					<div v-if="doc" class="preview-panel">
						<div class="preview-header">
							<div class="preview-title-row">
								<div
									class="preview-file-icon"
									:style="{ color: getTypeColor(doc.document_type) }"
								>
									<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"
										/>
									</svg>
								</div>
								<div class="preview-file-info">
									<h3 class="preview-file-name">{{ doc.file_name }}</h3>
									<span class="preview-file-meta">
										{{ formatType(doc.document_type) }} &middot;
										{{ formatFileSizeMb(doc.file_size_mb) }}
										<span
											class="preview-vis-badge"
											:class="'vis-' + (doc.visibility || 'public')"
										>
											&middot;
											{{
												(doc.visibility || "public")
													.charAt(0)
													.toUpperCase() +
												(doc.visibility || "public").slice(1)
											}}
										</span>
									</span>
								</div>
							</div>
							<div class="preview-actions">
								<button
									v-if="doc.is_owner"
									class="preview-action-btn"
									title="Manage access"
									aria-label="Manage access"
									@click="$emit('manage-access', doc)"
								>
									<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"
										/>
									</svg>
								</button>
								<button
									class="preview-action-btn"
									title="View chunks"
									aria-label="View chunks"
									@click="$emit('view-chunks', doc)"
								>
									<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M4 6h16M4 10h16M4 14h10M4 18h10"
										/>
									</svg>
								</button>
								<a :href="downloadUrl" class="preview-action-btn" title="Download">
									<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
										/>
									</svg>
								</a>
								<button
									class="preview-action-btn"
									title="Close"
									aria-label="Close"
									@click="$emit('close')"
								>
									<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M6 18L18 6M6 6l12 12"
										/>
									</svg>
								</button>
							</div>
						</div>
						<div class="preview-body">
							<div v-if="loading" class="preview-loading">
								<div class="loading-spinner"></div>
								<p>Loading preview...</p>
							</div>
							<iframe
								v-else-if="doc.document_type === 'PDF'"
								:src="contentUrl"
								class="pdf-preview"
								:title="doc.file_name"
							></iframe>
							<div
								v-else-if="doc.document_type === 'Markdown' && content !== null"
								class="markdown-preview"
								v-html="renderedMarkdown"
							></div>
							<pre v-else-if="content !== null" class="text-preview">{{
								content
							}}</pre>
						</div>
					</div>
				</Transition>
			</div>
		</Transition>
	</Teleport>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from "vue";
import { marked } from "marked";
import DOMPurify from "dompurify";
import { formatFileSizeMb } from "@/composables/useFormatters";
import { api } from "@/api/client";

const props = defineProps({
	doc: { type: Object, default: null },
});

const emit = defineEmits(["close", "manage-access", "view-chunks"]);

const content = ref(null);
const loading = ref(false);

// PDFs generated by the generate_document tool arrive with a Frappe file_url
// (e.g. "/private/files/Report.pdf") but no RAG document_id — those rows live
// in the File doctype, not AR Document. Fall back to file_url so the iframe
// and download button work for both RAG-indexed and ad-hoc generated files.
const contentUrl = computed(() => {
	if (props.doc?.document_id) return api.documents.getContentUrl(props.doc.document_id);
	if (props.doc?.file_url) return props.doc.file_url;
	return null;
});

const downloadUrl = computed(() => {
	if (props.doc?.document_id) return api.documents.getDownloadUrl(props.doc.document_id);
	if (props.doc?.file_url) return props.doc.file_url;
	return null;
});

const renderedMarkdown = computed(() => {
	if (!content.value) return "";
	const raw = marked.parse(content.value);
	return DOMPurify.sanitize(raw);
});

function getTypeColor(type) {
	if (!type) return "#6b7280";
	const t = type.toLowerCase();
	if (t === "pdf") return "#ef4444";
	if (t === "markdown" || t === "md") return "var(--ql-accent)";
	return "#6b7280";
}

function formatType(type) {
	if (!type) return "?";
	const t = type.toLowerCase();
	if (t === "pdf") return "PDF";
	if (t === "markdown") return "MD";
	if (t === "text") return "TXT";
	return type;
}

async function fetchContent(doc) {
	content.value = null;
	loading.value = false;

	if (!doc || doc.document_type === "PDF") return;

	const url = doc.document_id ? api.documents.getContentUrl(doc.document_id) : null;
	if (!url) return;

	loading.value = true;
	try {
		const response = await fetch(url);
		if (!response.ok) throw new Error("Failed to fetch file");
		content.value = await response.text();
	} catch {
		content.value = "Unable to load file content.";
	} finally {
		loading.value = false;
	}
}

watch(
	() => props.doc,
	(newDoc) => {
		if (newDoc) fetchContent(newDoc);
		else {
			content.value = null;
			loading.value = false;
		}
	},
	{ immediate: true }
);

function handleKeydown(e) {
	if (e.key === "Escape" && props.doc) {
		emit("close");
	}
}

onMounted(() => document.addEventListener("keydown", handleKeydown));
onUnmounted(() => document.removeEventListener("keydown", handleKeydown));
</script>

<style scoped>
.preview-backdrop {
	position: fixed;
	inset: 0;
	z-index: 1050;
	background-color: rgba(0, 0, 0, 0.4);
	backdrop-filter: blur(4px);
	display: flex;
	justify-content: flex-end;
}

.preview-panel {
	width: 560px;
	max-width: 100%;
	height: 100%;
	background: var(--ql-surface);
	border-left: 1px solid var(--ql-border);
	display: flex;
	flex-direction: column;
	box-shadow: -8px 0 24px rgba(0, 0, 0, 0.12);
}

.preview-header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 1rem 1.25rem;
	border-bottom: 1px solid var(--ql-border);
	gap: 0.75rem;
	flex-shrink: 0;
}

.preview-title-row {
	display: flex;
	align-items: center;
	gap: 0.625rem;
	min-width: 0;
	flex: 1;
}

.preview-file-icon {
	width: 1.5rem;
	height: 1.5rem;
	flex-shrink: 0;
}

.preview-file-icon svg {
	width: 100%;
	height: 100%;
}

.preview-file-info {
	min-width: 0;
}

.preview-file-name {
	font-size: 0.875rem;
	font-weight: 600;
	color: var(--ql-text);
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
	margin: 0;
}

.preview-file-meta {
	font-size: 0.75rem;
	color: var(--ql-text-muted);
}

.preview-vis-badge.vis-public {
	color: var(--ql-success);
}
.preview-vis-badge.vis-private {
	color: #f59e0b;
}
.preview-vis-badge.vis-shared {
	color: var(--ql-accent);
}

.preview-actions {
	display: flex;
	align-items: center;
	gap: 0.25rem;
	flex-shrink: 0;
}

.preview-action-btn {
	width: 2rem;
	height: 2rem;
	padding: 0.375rem;
	background: none;
	border: none;
	color: var(--ql-text-muted);
	cursor: pointer;
	border-radius: 0.375rem;
	transition: all 0.15s ease;
	display: flex;
	align-items: center;
	justify-content: center;
	text-decoration: none;
}

.preview-action-btn svg {
	width: 100%;
	height: 100%;
}

.preview-action-btn:hover {
	color: var(--ql-text);
	background: var(--ql-subtle);
}

.preview-body {
	flex: 1;
	overflow: auto;
	scrollbar-width: thin;
	scrollbar-color: var(--ql-border) transparent;
}

.preview-loading {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	height: 100%;
	gap: 1rem;
}

.preview-loading p {
	font-size: 0.875rem;
	color: var(--ql-text-muted);
}

.loading-spinner {
	width: 2rem;
	height: 2rem;
	border: 2px solid var(--ql-border);
	border-top-color: var(--ql-accent);
	border-radius: 50%;
	animation: spin 0.8s linear infinite;
}

@keyframes spin {
	to {
		transform: rotate(360deg);
	}
}

.pdf-preview {
	width: 100%;
	height: 100%;
	border: none;
}

.markdown-preview {
	padding: 1.5rem;
	font-size: 0.875rem;
	line-height: 1.7;
	color: var(--ql-text);
}

.markdown-preview :deep(h1) {
	font-size: 1.5rem;
	font-weight: 700;
	margin: 1.5rem 0 0.75rem;
	color: var(--ql-text);
}
.markdown-preview :deep(h2) {
	font-size: 1.25rem;
	font-weight: 600;
	margin: 1.25rem 0 0.5rem;
	color: var(--ql-text);
	border-bottom: 1px solid var(--ql-border);
	padding-bottom: 0.375rem;
}
.markdown-preview :deep(h3) {
	font-size: 1.1rem;
	font-weight: 600;
	margin: 1rem 0 0.5rem;
	color: var(--ql-text);
}
.markdown-preview :deep(p) {
	margin: 0 0 0.75rem;
}
.markdown-preview :deep(ul),
.markdown-preview :deep(ol) {
	padding-left: 1.5rem;
	margin: 0 0 0.75rem;
}
.markdown-preview :deep(ul) {
	list-style: disc;
}
.markdown-preview :deep(ol) {
	list-style: decimal;
}
.markdown-preview :deep(li) {
	margin-bottom: 0.25rem;
}
.markdown-preview :deep(code) {
	font-size: 0.8125rem;
	background: var(--ql-subtle);
	padding: 0.125rem 0.375rem;
	border-radius: 0.25rem;
}
.markdown-preview :deep(pre) {
	background: var(--ql-subtle);
	padding: 1rem;
	border-radius: 0.5rem;
	overflow-x: auto;
	margin: 0.75rem 0;
}
.markdown-preview :deep(pre code) {
	background: none;
	padding: 0;
}
.markdown-preview :deep(blockquote) {
	border-left: 3px solid var(--ql-border);
	padding: 0.5rem 1rem;
	margin: 0.75rem 0;
	color: var(--ql-text-secondary);
}
.markdown-preview :deep(table) {
	width: 100%;
	border-collapse: collapse;
	margin: 0.75rem 0;
	font-size: 0.8125rem;
}
.markdown-preview :deep(th) {
	background: var(--ql-subtle);
	text-align: left;
	padding: 0.5rem 0.75rem;
	border: 1px solid var(--ql-border);
	font-weight: 600;
}
.markdown-preview :deep(td) {
	padding: 0.5rem 0.75rem;
	border: 1px solid var(--ql-border);
}
.markdown-preview :deep(a) {
	color: var(--ql-accent);
	text-decoration: none;
}
.markdown-preview :deep(a:hover) {
	text-decoration: underline;
}
.markdown-preview :deep(hr) {
	border: none;
	border-top: 1px solid var(--ql-border);
	margin: 1rem 0;
}
.markdown-preview :deep(img) {
	max-width: 100%;
	border-radius: 0.375rem;
}

.text-preview {
	padding: 1.5rem;
	font-size: 0.8125rem;
	line-height: 1.6;
	color: var(--ql-text);
	white-space: pre-wrap;
	word-wrap: break-word;
	margin: 0;
	font-family: "SF Mono", "Fira Code", "Consolas", monospace;
	background: transparent;
}

/* Transitions */
.preview-fade-enter-active,
.preview-fade-leave-active {
	transition: opacity 0.2s ease;
}
.preview-fade-enter-from,
.preview-fade-leave-to {
	opacity: 0;
}

.preview-slide-enter-active {
	transition: transform 0.25s ease-out;
}
.preview-slide-leave-active {
	transition: transform 0.2s ease-in;
}
.preview-slide-enter-from {
	transform: translateX(100%);
}
.preview-slide-leave-to {
	transform: translateX(100%);
}

@media (max-width: 768px) {
	.preview-panel {
		width: 100%;
	}
}
</style>
