/**
 * Composable for fetching and managing AI-generated memory narrative summaries.
 *
 * The summary is generated by an LLM from the user's memory fragments and
 * cached on the backend, which serves the last one immediately and refreshes
 * it behind the request when memories have changed.
 *
 * The browser keeps its own copy on top of that, because even a server cache
 * hit costs a round trip through the customer's site to the cloud. The last
 * summary is painted the moment the tab mounts — before the request is sent —
 * and the response swaps in underneath. `summaryLoading` is therefore only
 * true when there is genuinely nothing to show: a skeleton over content the
 * user already had is a downgrade, not a loading state.
 */

import { ref } from "vue";
import { api } from "@/api/client";
import { logger } from "@/utils/logger";

const STORAGE_PREFIX = "pao_memory_summary:";

function storageKey(userId) {
	return `${STORAGE_PREFIX}${userId || "anonymous"}`;
}

/**
 * The summary is markdown prose. Entries generated before the server stopped
 * asking the model for JSON are envelopes instead, and painting one would put
 * raw braces on screen for the whole round trip. The server repairs its own
 * copy, so the skeleton here is only ever a moment long — cheaper than
 * mirroring the unwrapping in a second language.
 */
function isProse(text) {
	const start = text.trimStart();
	return !start.startsWith("```") && !start.startsWith("{") && !start.startsWith("[");
}

/**
 * Storage is best-effort throughout: Safari private mode throws on write, a
 * full quota throws, and a corrupted entry should be discarded rather than
 * crash the tab. None of that is worth failing a page over — the worst case
 * is the pre-existing behaviour of waiting for the network.
 */
function readCached(userId) {
	try {
		return localStorage.getItem(storageKey(userId)) || null;
	} catch {
		return null;
	}
}

function writeCached(userId, summary) {
	try {
		if (summary) {
			localStorage.setItem(storageKey(userId), summary);
		} else {
			localStorage.removeItem(storageKey(userId));
		}
	} catch {
		// Non-fatal — we simply lose the instant paint on the next visit.
	}
}

export function useMemorySummary(userId) {
	const summary = ref(null);
	const summaryLoading = ref(false);
	const summaryError = ref(null);
	// True while the server is regenerating behind the copy being shown, so
	// the UI can say "updating" instead of implying the text is current.
	const summaryStale = ref(false);

	function cacheSummary(text) {
		summary.value = text || null;
		writeCached(userId, text);
	}

	function applyResult(result) {
		if (result?.summary) {
			summary.value = result.summary;
			summaryStale.value = !!result.stale;
			writeCached(userId, result.summary);
			return;
		}
		// A definite "no summary" — not enough memories, or the tenant has
		// none. Drop the browser copy so a profile the server no longer
		// stands behind cannot keep reappearing.
		summary.value = null;
		summaryStale.value = false;
		writeCached(userId, null);
	}

	async function fetchSummary(force) {
		// Paint what we already have first; only an empty view gets a skeleton.
		const cached = readCached(userId);
		if (cached && !isProse(cached)) {
			writeCached(userId, null);
		} else if (cached && !force) {
			summary.value = cached;
		}
		summaryLoading.value = !summary.value;
		summaryError.value = null;

		try {
			applyResult(await api.memories.getSummary(force));
		} catch (err) {
			logger.error("Failed to load memory summary:", err);
			// A failed refresh must not take away a summary the user can
			// still read. Only report the error when it leaves them with
			// nothing.
			if (!summary.value) {
				summaryError.value = force
					? "Failed to regenerate summary"
					: "Failed to load summary";
			}
		} finally {
			summaryLoading.value = false;
		}
	}

	function loadSummary() {
		return fetchSummary(false);
	}

	function regenerateSummary() {
		return fetchSummary(true);
	}

	function clearSummary() {
		summary.value = null;
		summaryStale.value = false;
		writeCached(userId, null);
	}

	return {
		summary,
		summaryLoading,
		summaryError,
		summaryStale,
		loadSummary,
		regenerateSummary,
		clearSummary,
		cacheSummary,
	};
}
