import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("@/api/client", () => ({
	api: {
		memories: {
			getSummary: vi.fn(),
		},
	},
}));

vi.mock("@/utils/logger", () => ({
	logger: { error: vi.fn(), warn: vi.fn(), info: vi.fn() },
}));

import { api } from "@/api/client";
import { useMemorySummary } from "@/composables/useMemorySummary.js";

const USER = "paul@example.com";

/** A promise the test resolves by hand, so "still in flight" is observable. */
function deferred() {
	let resolve;
	const promise = new Promise((r) => {
		resolve = r;
	});
	return { promise, resolve };
}

beforeEach(() => {
	localStorage.clear();
	vi.clearAllMocks();
});

/**
 * The summary is generated by an LLM and the server cache is invalidated on
 * every memory write, so a plain fetch-on-mount meant a multi-second skeleton
 * nearly every visit. The last summary is kept in the browser and painted
 * before the request is even sent.
 */
describe("instant paint from the browser cache", () => {
	it("shows the previous summary before the request resolves", async () => {
		const { promise, resolve } = deferred();
		api.memories.getSummary.mockReturnValue(promise);

		const first = useMemorySummary(USER);
		first.cacheSummary("Profile from last visit");

		const second = useMemorySummary(USER);
		second.loadSummary();

		// Painted synchronously — no await between mount and content.
		expect(second.summary.value).toBe("Profile from last visit");
		expect(second.summaryLoading.value).toBe(false);

		resolve({ summary: "Fresh from the server" });
		await promise;
	});

	it("still shows the skeleton when there is nothing cached to paint", () => {
		const { promise } = deferred();
		api.memories.getSummary.mockReturnValue(promise);

		const { summary, summaryLoading, loadSummary } = useMemorySummary(USER);
		loadSummary();

		expect(summary.value).toBeNull();
		expect(summaryLoading.value).toBe(true);
	});

	it("replaces the painted copy once the server answers", async () => {
		const { summary, loadSummary, cacheSummary } = useMemorySummary(USER);
		cacheSummary("Old text");
		api.memories.getSummary.mockResolvedValue({ summary: "New text" });

		await loadSummary();

		expect(summary.value).toBe("New text");
	});

	it("keeps showing the cached copy when the request fails", async () => {
		const { summary, summaryError, loadSummary, cacheSummary } = useMemorySummary(USER);
		cacheSummary("Old but useful");
		api.memories.getSummary.mockRejectedValue(new Error("offline"));

		await loadSummary();

		expect(summary.value).toBe("Old but useful");
		expect(summaryError.value).toBeNull();
	});

	it("reports the error when there was nothing cached to fall back on", async () => {
		const { summary, summaryError, loadSummary } = useMemorySummary(USER);
		api.memories.getSummary.mockRejectedValue(new Error("offline"));

		await loadSummary();

		expect(summary.value).toBeNull();
		expect(summaryError.value).toBeTruthy();
	});

	it("does not serve one user's summary to another", () => {
		const mine = useMemorySummary(USER);
		mine.cacheSummary("My profile");

		api.memories.getSummary.mockReturnValue(deferred().promise);
		const theirs = useMemorySummary("someone.else@example.com");
		theirs.loadSummary();

		expect(theirs.summary.value).toBeNull();
	});
});

describe("staleness", () => {
	it("surfaces the server's stale flag so the UI can say it is updating", async () => {
		const { summaryStale, loadSummary } = useMemorySummary(USER);
		api.memories.getSummary.mockResolvedValue({
			summary: "Text",
			stale: true,
		});

		await loadSummary();

		expect(summaryStale.value).toBe(true);
	});

	it("clears the stale flag once a fresh summary arrives", async () => {
		const { summaryStale, loadSummary } = useMemorySummary(USER);
		api.memories.getSummary.mockResolvedValueOnce({ summary: "Text", stale: true });
		await loadSummary();

		api.memories.getSummary.mockResolvedValueOnce({ summary: "Text", stale: false });
		await loadSummary();

		expect(summaryStale.value).toBe(false);
	});
});

describe("clearing", () => {
	it("forgets the browser copy so a deleted profile cannot reappear", () => {
		const { summary, clearSummary, cacheSummary } = useMemorySummary(USER);
		cacheSummary("Profile text");

		clearSummary();

		expect(summary.value).toBeNull();
		const revisit = useMemorySummary(USER);
		api.memories.getSummary.mockReturnValue(deferred().promise);
		revisit.loadSummary();
		expect(revisit.summary.value).toBeNull();
	});

	it("caches a regenerated summary too", async () => {
		const { regenerateSummary } = useMemorySummary(USER);
		api.memories.getSummary.mockResolvedValue({ summary: "Regenerated" });

		await regenerateSummary();

		const revisit = useMemorySummary(USER);
		api.memories.getSummary.mockReturnValue(deferred().promise);
		revisit.loadSummary();
		expect(revisit.summary.value).toBe("Regenerated");
	});

	it("survives a browser that refuses to store anything", () => {
		const setItem = vi
			.spyOn(Storage.prototype, "setItem")
			.mockImplementation(() => {
				throw new Error("QuotaExceededError");
			});

		const { cacheSummary } = useMemorySummary(USER);
		expect(() => cacheSummary("Profile")).not.toThrow();

		setItem.mockRestore();
	});
});

/**
 * Summaries generated before the server stopped borrowing the extraction
 * system prompt are JSON envelopes, not prose. The server repairs its own
 * copy, but a browser holding one would paint it on mount — raw braces and
 * all — for the whole round trip. A cached entry that is plainly not prose is
 * worth less than the skeleton that replaces it.
 */
describe("a cached entry that is not prose", () => {
	it("is not painted on mount", () => {
		localStorage.setItem(
			`pao_memory_summary:${USER}`,
			'```json\n{"profile": {"work_context": "## Work context\\nThey ship."}}\n```',
		);

		const { summary, summaryLoading, loadSummary } = useMemorySummary(USER);
		api.memories.getSummary.mockReturnValue(deferred().promise);
		loadSummary();

		expect(summary.value).toBeNull();
		expect(summaryLoading.value).toBe(true);
	});

	it("is discarded from storage so it cannot come back", () => {
		localStorage.setItem(`pao_memory_summary:${USER}`, '{"profile": {}}');

		const { loadSummary } = useMemorySummary(USER);
		api.memories.getSummary.mockReturnValue(deferred().promise);
		loadSummary();

		expect(localStorage.getItem(`pao_memory_summary:${USER}`)).toBeNull();
	});

	it("still paints a summary that merely starts with a heading", () => {
		localStorage.setItem(`pao_memory_summary:${USER}`, "## Work context\nThey ship.");

		const { summary, loadSummary } = useMemorySummary(USER);
		api.memories.getSummary.mockReturnValue(deferred().promise);
		loadSummary();

		expect(summary.value).toBe("## Work context\nThey ship.");
	});
});
